defaults:
  - logger: logger
  - arch: anakin
  - system: mat/mat
  - network: transformer
  - env: rware # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs

system:
  # BYOL parameters
  use_byol: False  # Whether to use BYOL
  target_network_ema: 0.99  # EMA update coefficient for target networks
  byol_coef: 1  # BYOL loss coefficient
  fdm_seq_len: 2
  fdm_period: 1
  fdm_batch_size: 512
  fdm_max_length: 10000
  fdm_min_length: 128
  fdm_lr: 1e-5
